blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions / è®¨è®ºåŒº
    url: https://github.com/CharlesPikachu/videodl/discussions
    about: Please ask and answer questions here. / å»ºè®®åœ¨è®¨è®ºåŒºæé—®ä¸äº¤æµã€‚
  - name: ğŸ”’ Security / å®‰å…¨é—®é¢˜
    url: https://github.com/CharlesPikachu/videodl/security/policy
    about: Please report security vulnerabilities privately. / å®‰å…¨æ¼æ´è¯·ç§ä¸‹æäº¤ã€‚